name: empresas_flutter
description: A new Flutter project.

publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_redux: ^0.7.0
  built_value: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  built_value_generator: any
  build_runner: any

flutter:

  uses-material-design: true